export const END_ADDING_METRIC = 'END_ADDING_METRIC';
export const START_ADDING_KU = 'START_ADDING_KU';
export const END_ADDING_KU = 'END_ADDING_KU';
export const START_ADDING_METRIC = 'START_ADDING_METRIC';

export const CLOSE_MODAL_FAQ = 'CLOSE_MODAL_FAQ';
export const SHOW_MODAL_FAQ = 'SHOW_MODAL_FAQ';
export const SHOW_MODAL_INTRODUCTION = 'SHOW_MODAL_INTRODUCTION'
export const SHOW_MODAL_METRIC = 'SHOW_MODAL_METRIC';
export const CLOSE_MODAL_METRIC = 'CLOSE_MODAL_METRIC';
export const CLOSE_MODAL_KU = 'CLOSE_MODAL_KU';
export const CLOSE_MODAL_SECTION = 'CLOSE_MODAL_SECTION';
export const CLOSE_MODAL_INTRODUCTION = 'CLOSE_MODAL_INTRODUCTION';
export const END_ADDING_SECTION = 'END_ADDING_SECTION';
export const SHOW_MODAL_KU = 'SHOW_MODAL_KU';
export const SHOW_MODAL_SECTION = 'SHOW_MODAL_SECTION';
export const START_ADDING_SECTION = 'START_ADDING_SECTION';