export const GET_MELIMETRIC_DATA = 'GET_MELIMETRIC_DATA';
export const GET_MELIMETRIC_DATA_DETAILL = 'GET_MELIMETRIC_DATA';
export const NOTIFICATION_READ = 'NOTIFICATION_READ';
export const ERROR_LOAD_NOTIFICATION = 'ERROR_LOAD_NOTIFICATION';
export const ACTIVE_NOTIFICATION = 'ACTIVE_NOTIFICATION';
export const NOTIFICATION_LOADED = 'NOTIFICATION_LOADED';
export const START_LOAD_NOTIFICATION = 'START_LOAD_NOTIFICATION';
