
const initialStore = {
  userName: undefined,
  loginUserSucces: false,
  toggleDrawer: true,
  toggleDrawerBody: false,
  showMetrics: false,
  showAttributes: false,
  showResume: false,
  modalSection: false,
  modalFaq: false,
  modalIntroduction: false,
  modalKeyUser: false,
  modalMetric: false,
  buId: undefined,
  buName: undefined,
  currentSection: undefined,
  isAdmin: true,
  introduction: { title: undefined, description: undefined },
  key_users: {},
  sections: {},
  faqs: [],
  currentDashboard: undefined,
  isLoading: true,
  role: undefined,
  isEditing: false,
  isAddingSection: false,
  isAddingKu: false,
  isAddingFAQ: false,
  search: {},
  dashboards: undefined,
  isModifyingIntroduction: false,
  currentSectionPath: undefined,
  isAddingMetric: false,
  currentPage: 'search',
  currentPageAdmin: 'asignarSeccion',
  currentDashboardAdmin: undefined,
  resultAddingMetric: undefined,
  recentDashboard: undefined,
  favourites: [],
  metrics: [],
  metricData: [],
  messageMelimetric:false,
  metricSelected:[],
  newConfiguration:[],
  userConfig:undefined,
  metricConfigurations: [],
  existingMetrics: {},
  detail: [],
  selected: [],
  meliMetricAlert: {
    alert:false, 
    metric_data:{id:undefined, metric_name:undefined},
    alert_data:[],
  },
  tools: [
    { name: 'Tableau', icon: 'https://i.ibb.co/KK51cHx/tools-img-01.png', url: 'https://tableau.adminml.com' },
    { name: 'Gaia', icon: 'https://i.ibb.co/bP3JqfB/tools-img-02.png', url: 'http://gaia.ml.com' },
    { name: 'Alation', icon: 'https://i.ibb.co/By4qYQ5/tools-img-03.png', url: 'http://alation.ml.com' },
    { name: 'MicroStrategy', icon: 'https://i.ibb.co/5xC1RNW/tools-img-04.png', url: 'https://bi.mercadolibre.com' },
    { name: 'BI-Licensing', icon: 'https://i.ibb.co/4tBhpmT/tools-img-05.png', url: 'http://bi-licensing.ml.com' }
  ],
  notification:{list:undefined,status:undefined},
};


export default initialStore;
