export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const END_ADDING_FAQ = 'END_ADDING_FAQ';
export const START_ADDING_FAQ = 'START_ADDING_FAQ';
export const DASHBOARD_SELECTED = 'DASHBOARD_SELECTED';